[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "test-pypi"           # Ne changez pas ce nom pour l'instant
version = "0.0.5"
description = "Test d'initialisation"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Louis Clavel" }]


[tool.setuptools]
packages = [] # Important pour un dummy package
